spring:
  profiles:
    active:
    - dev
    
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/pcr
#    username: postgres
#    password: {YOUR_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#kakaoKey : {YOUR_KAKAO_API_KEY}

#logging:
#  level:
#    root: debug